# 1. Основы NumPy - Демонстрация работы с библиотекой NumPy и матрицами

## Создание и преобразование матриц

### Подключение библиотеки и создание матрицы

In [2]:
import numpy as np

a1 = np.array([[1,2,3], [4,5,6]])
print(a1)
print("размерность: " + str(a1.shape))

[[1 2 3]
 [4 5 6]]
размерность: (2, 3)


### Транспонирование матрицы

In [15]:
aT = a1.T
print(aT)
print("размерность: " + str(aT.shape))

[[1 4]
 [2 5]
 [3 6]]
размерность: (3, 2)


### Создание единичной матрицы

In [18]:
e1 = 2 * np.eye(3, 4, k=0)
# k - сдвиг относительно главной диагонали
print("----- e1 -----")
print(e1)

e2 = np.eye(3, 4, k=1)
print("----- e2 -----")
print(e2)

print("--- e1 + e2 ---")
print(e1 + e2)

----- e1 -----
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]]
----- e2 -----
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--- e1 + e2 ---
[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


### Перевод в одномерный массив

In [17]:
a2 = a1.flatten()
print("--- до ---")
print(a1)
print("--- после ---")
print(a2)
print("размерность: " + str(a2.shape))

--- до ---
[[1 2 3]
 [4 5 6]]
--- после ---
[1 2 3 4 5 6]
размерность: (6,)


### Изменение формы матрицы

In [19]:
a3 = np.reshape(a2, (a2.size, 1))
print("--- до ---")
print(a2)
print("--- после ---")
print(a3)
print("размерность: " + str(a3.shape))

--- до ---
[1 2 3 4 5 6]
--- после ---
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
размерность: (6, 1)


## Базовые статистики

In [6]:
import random

v = np.array(random.sample(range(8), 8))
print(v)
v = v.reshape((2,4))
print(v)
print("--- вывод базовых статистик матрицы ---")

print("вдоль столбцов:")
print("mean: " + str(v.mean(axis=0)))
print(" max: " + str(v.max(axis=0)))
print(" min: " + str(v.min(axis=0)))

print("вдоль строк:")
print("mean: " + str(v.mean(axis=1)))
print(" max: " + str(v.max(axis=1)))
print(" min: " + str(v.min(axis=1)))

print("вдоль всего массива:")
print("mean: " + str(v.mean(axis=None)))
print(" max: " + str(v.max(axis=None)))
print(" min: " + str(v.min(axis=None)))

[0 5 7 4 2 6 3 1]
[[0 5 7 4]
 [2 6 3 1]]
--- вывод базовых статистик матрицы ---
вдоль столбцов:
mean: [1.  5.5 5.  2.5]
 max: [2 6 7 4]
 min: [0 5 3 1]
вдоль строк:
mean: [4. 3.]
 max: [7 6]
 min: [0 1]
вдоль всего массива:
mean: 3.5
 max: 7
 min: 0
